// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: customers.proto

package plantmanager

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1CustomersMock struct{}

func (m *V1CustomersMock) GetCustomer(ctx context.Context, req *GetCustomerRequest) (*GetCustomerReply, error) {
	res :=
		&GetCustomerReply{
			Customer: &Customer{
				Id:   437,
				Name: "corrupti",
			},
		}
	return res, nil
}
func (m *V1CustomersMock) FindCustomers(ctx context.Context, req *FindCustomersRequest) (*FindCustomersReply, error) {
	res :=
		&FindCustomersReply{
			Customers: []*Customer{
				&Customer{
					Id:   308,
					Name: "amet",
				},
				&Customer{
					Id:   952,
					Name: "dolore",
				},
				&Customer{
					Id:   914,
					Name: "quis",
				},
				&Customer{
					Id:   791,
					Name: "non",
				},
				&Customer{
					Id:   586,
					Name: "ipsum",
				},
				&Customer{
					Id:   199,
					Name: "fuga",
				},
				&Customer{
					Id:   732,
					Name: "voluptatem",
				},
				&Customer{
					Id:   658,
					Name: "labore",
				},
			},
		}
	return res, nil
}
func (m *V1CustomersMock) CreateCustomer(ctx context.Context, req *CreateCustomerRequest) (*CreateCustomerReply, error) {
	res :=
		&CreateCustomerReply{
			Customer: &Customer{
				Id:   6,
				Name: "porro",
			},
		}
	return res, nil
}
func (m *V1CustomersMock) DestroyCustomer(ctx context.Context, req *DestroyCustomerRequest) (*EmptyReply, error) {
	res :=
		&EmptyReply{}
	return res, nil
}
