// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: placements.proto

package plantmanager

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1PlacesMock struct{}

func (m *V1PlacesMock) GetPlace(ctx context.Context, req *GetPlaceRequest) (*GetPlaceReply, error) {
	res :=
		&GetPlaceReply{
			Place: &Place{
				Id:   93,
				Name: "nam",
			},
		}
	return res, nil
}
func (m *V1PlacesMock) FindPlaces(ctx context.Context, req *FindPlacesRequest) (*FindPlacesReply, error) {
	res :=
		&FindPlacesReply{
			Places: []*Place{
				&Place{
					Id:   953,
					Name: "voluptatem",
				},
				&Place{
					Id:   639,
					Name: "vel",
				},
				&Place{
					Id:   202,
					Name: "asperiores",
				},
				&Place{
					Id:   521,
					Name: "harum",
				},
				&Place{
					Id:   378,
					Name: "praesentium",
				},
				&Place{
					Id:   183,
					Name: "optio",
				},
				&Place{
					Id:   95,
					Name: "dicta",
				},
				&Place{
					Id:   894,
					Name: "accusamus",
				},
			},
		}
	return res, nil
}
func (m *V1PlacesMock) CreatePlace(ctx context.Context, req *CreatePlaceRequest) (*CreatePlaceReply, error) {
	res :=
		&CreatePlaceReply{
			Place: &Place{
				Id:   20,
				Name: "quaerat",
			},
		}
	return res, nil
}
func (m *V1PlacesMock) DestroyPlace(ctx context.Context, req *DestroyPlaceRequest) (*EmptyReply, error) {
	res :=
		&EmptyReply{}
	return res, nil
}
