// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: varieties.proto

package plantmanager

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1VarietiesMock struct{}

func (m *V1VarietiesMock) GetVariety(ctx context.Context, req *GetVarietyRequest) (*GetVarietyReply, error) {
	res :=
		&GetVarietyReply{
			Variety: &Variety{
				Id:          51,
				Name:        "nobis",
				PlantTypeId: 575,
				CustomerId:  608,
			},
		}
	return res, nil
}
func (m *V1VarietiesMock) FindVarieties(ctx context.Context, req *FindVarietiesRequest) (*FindVarietiesReply, error) {
	res :=
		&FindVarietiesReply{
			Varieties: []*Variety{
				&Variety{
					Id:          530,
					Name:        "hic",
					PlantTypeId: 269,
					CustomerId:  539,
				},
				&Variety{
					Id:          36,
					Name:        "perferendis",
					PlantTypeId: 269,
					CustomerId:  18,
				},
				&Variety{
					Id:          572,
					Name:        "omnis",
					PlantTypeId: 21,
					CustomerId:  295,
				},
				&Variety{
					Id:          431,
					Name:        "rem",
					PlantTypeId: 840,
					CustomerId:  490,
				},
				&Variety{
					Id:          750,
					Name:        "officia",
					PlantTypeId: 757,
					CustomerId:  615,
				},
				&Variety{
					Id:          732,
					Name:        "voluptatem",
					PlantTypeId: 808,
					CustomerId:  615,
				},
				&Variety{
					Id:          314,
					Name:        "provident",
					PlantTypeId: 928,
					CustomerId:  902,
				},
				&Variety{
					Id:          993,
					Name:        "laboriosam",
					PlantTypeId: 430,
					CustomerId:  862,
				},
			},
		}
	return res, nil
}
func (m *V1VarietiesMock) CreateVariety(ctx context.Context, req *CreateVarietyRequest) (*CreateVarietyReply, error) {
	res :=
		&CreateVarietyReply{
			Variety: &Variety{
				Id:          204,
				Name:        "qui",
				PlantTypeId: 513,
				CustomerId:  216,
			},
		}
	return res, nil
}
func (m *V1VarietiesMock) UpdateVariety(ctx context.Context, req *UpdateVarietyRequest) (*EmptyReply, error) {
	res :=
		&EmptyReply{}
	return res, nil
}
func (m *V1VarietiesMock) DestroyVariety(ctx context.Context, req *DestroyVarietyRequest) (*EmptyReply, error) {
	res :=
		&EmptyReply{}
	return res, nil
}
